#!/bin/sh

[ ! -f /etc/ssh/ssh_host_key ]         && ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key     -N "" -C ""
[ ! -f /etc/ssh/ssh_host_rsa_key ]     && ssh-keygen -t rsa  -f /etc/ssh/ssh_host_rsa_key -N "" -C ""
[ ! -f /etc/ssh/ssh_host_dsa_key ]     && ssh-keygen -t dsa  -f /etc/ssh/ssh_host_dsa_key -N "" -C ""
[ ! -f /etc/ssh/ssh_host_ecdsa_key ]   && ssh-keygen -t ecdsa  -f /etc/ssh/ssh_host_ecdsa_key -N "" -C ""
[ ! -f /etc/ssh/ssh_host_ed25519_key ] && ssh-keygen -t ed25519  -f /etc/ssh/ssh_host_ed25519_key -N "" -C ""

exit 0
