#!/bin/sh

if [ -f /etc/lighttpd ]
then
   echo""
else
   mkdir -p /etc/lighttpd
fi


#During a package upgrade, the old packages scripts will stop and don't restart 'lighttpd' -> Damn!
#Therefore we have to restart it again ....
if [ -f /Library/LaunchDaemons/com.atv.lighttpd.plist  ]
then
   launchctl load -w /Library/LaunchDaemons/com.atv.lighttpd.plist
fi


echo " "
echo "If you have an own lighttpd config file, you can start the web server lighttpd with the command below:"
echo "/usr/sbin/lighttpd -f'path_to_your_config_file.conf'"
echo " "
echo "You can place your Lighttpd config file in /etc/lighttpd/"
echo "You can place your web content in /var/www/"
echo " "

