#!/bin/sh

if [ $1 != upgrade ]; then
 if [ -d /var/www/owncloud ]; then
   rm -r /var/www/owncloud   
 fi
fi

if [ -f /etc/lighttpd/lighttpd-atv.conf ];then
  sed -i '/mod_owncloud/d' /etc/lighttpd/lighttpd-atv.conf
fi

if [ -f /etc/lighttpd.conf ];then
  sed -i '/mod_owncloud/d' /etc/lighttpd.conf
fi
 
exit 0

