#!/bin/sh
if [ -f /var/www/webalizer/index.html ]
then
   rm /var/www/webalizer/tk.webstack.ios.index.html
else
   mv /var/www/webalizer/tk.webstack.ios.index.html /var/www/webalizer/index.html
fi

exit 0

