#!/bin/sh

if [ $1 != upgrade ]; then
 rm /etc/php.ini
 rm -r /etc/php.d
 rm -r /etc/lighttpd
 rm /etc/lighttpd.conf
 rm -r /var/log/lighttpd
 rm /var/www/phpinfo.php
 rm /var/www/index.html

 declare -a cydia
 cydia=($CYDIA)
 if [[ ${CYDIA+@} ]]; then
    eval "echo 'finish:restart' >&${cydia[0]}"
 else
    echo "Please kill or restart 'Preferences'."
 fi

fi

exit 0

