#!/bin/sh

#Backup existing config files

#PHP
if [ -f /etc/php.ini ]
then
    mv /etc/php.ini /etc/php.ini.backup.`date +%Y%m%d.%T`
    echo ""
    echo "Your PHP config file is backed up to:"
    echo "/etc/php.ini.backup.Date+Time"
fi
if [ -f /etc/php.d/load_all.ini ]
then
    mv /etc/php.d/load_all.ini /etc/php.d/load_all.ini.backup.`date +%Y%m%d.%T`
    echo ""
    echo "Your Extension PHP config file is backed up to:"
    echo "/etc/php.d/load_all.ini.backup.Date+Time"
fi



#Lighttpd 
if [ -f /etc/lighttpd.conf ]
then
    mv /etc/lighttpd.conf /etc/lighttpd.conf.backup.`date +%Y%m%d.%T`
    echo ""
    echo "Your Lighttpd config file is backed up to:"
    echo "/etc/lighttpd.conf.backup.Date+Time"
fi

if [ -f /etc/lighttpd/lighttpd.conf ]
then
    mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.backup.`date +%Y%m%d.%T`
    echo ""
    echo "Your Lighttpd config file is backed up to:"
    echo "/etc/lighttpd/lighttpd.conf.backup.Date+Time"
fi



#PHP & Lighthttpd
if [ -f /etc/lighttpd/mod_fastcgi.conf  ]
then
    mv /etc/lighttpd/mod_fastcgi.conf /etc/lighttpd/mod_fastcgi.conf.backup.`date +%Y%m%d.%T`
    echo ""
    echo "Your PHP FastCGI config file is backed up to:"
    echo "/etc/lighttpd/mod_fastcgi.conf.backup.Date+Time"
fi


exit 0
