#!/bin/sh

#Prepar the onwCloud install script permissions
chown daemon:_www /var/www/setup-owncloud.php

#If we don't have write permissions in /var/www, we have to prepar something 
mkdir -p /var/www/owncloud
chown daemon:_www /var/www/owncloud

##check for an older installation and fix the permissions
#if [ -d /var/www/owncloud ]; then
#   chown daemon:_www /var/www/owncloud -R
#fi

# check for the installation typ (touch or atv/ios) and modify the lighttpd config file  
if [ -f /etc/lighttpd.conf ]; then
   echo ' ' >> /etc/lighttpd.conf
   echo 'include "lighttpd/mod_owncloud.conf"' >> /etc/lighttpd.conf

else
if [ -f /etc/lighttpd/lighttpd-atv.conf ]; then
   echo ' ' >> /etc/lighttpd/lighttpd-atv.conf
   echo 'include "mod_owncloud.conf"' >> /etc/lighttpd/lighttpd-atv.conf
fi
fi 

# Since ownCloud 5.x we need more the one PHP child instance.
# check for mod_fastcgi-atv.conf
if [ -f /etc/lighttpd/mod_fastcgi-atv.conf ]; then
      sed -i 's/"PHP_FCGI_CHILDREN" => "1"/"PHP_FCGI_CHILDREN" => "2" #need it for ownCloud >= 5/' /etc/lighttpd/mod_fastcgi-atv.conf
fi

echo " "
echo "You must restart your Lighttpd server!!!"
echo " "
echo "After that, please open Safari at your iOS Device and type in 'http://localhost/setup-owncloud.php'."
echo "After the installation you will find your ownCloud at 'http://your_ios_device/owncloud'."
echo " "
echo "Again: You must restart your Lighttpd server!!!"
echo " "

exit 0
