#!/bin/sh

if [ $1 == remove ]; then
 if [ -d /var/www/owncloud ]; then
   rm -r /var/www/owncloud   
 fi
fi

if [ -f /etc/lighttpd/lighttpd-atv.conf ];then
  sed -i '/mod_owncloud/d' /etc/lighttpd/lighttpd-atv.conf
fi

if [ -f /etc/lighttpd.conf ];then
  sed -i '/mod_owncloud/d' /etc/lighttpd.conf
fi

if [ -f /etc/lighttpd/mod_fastcgi-atv.conf ]; then
      sed -i 's/"PHP_FCGI_CHILDREN" => "2" #need it for ownCloud >= 5/"PHP_FCGI_CHILDREN" => "1"/' /etc/lighttpd/mod_fastcgi-atv.conf
fi

 
exit 0

