#!/bin/sh

launchctl unload -w /Library/LaunchDaemons/com.atv.lighttpd.plist 2>&1 | true
launchctl unload -w /Library/LaunchDaemons/com.atv.mysql.plist 2>&1 | true


#Dobble Check

LIGHTTPD=`ps -ax | grep '[l]ighttpd' | grep 'sbin' | awk '{ print $1 }'`
if [ "$LIGHTTPD" != "" ]; then
 kill -s TERM $LIGHTTPD
fi

MYSQL=`ps -ax | grep '[m]ysql' | grep 'libexec' | awk '{ print $1 }'`
if [ "$MYSQL" != "" ]; then
 kill -s TERM $MYSQL
fi


exit 0

