#!/bin/sh

if [ $1 != upgrade ]; then
 if [ -d /var/www/typo3_introduction ]; then
   rm -r /var/www/typo3_introduction
 fi
fi

if [ -f /etc/lighttpd/lighttpd-atv.conf ];then
  sed -i '/mod_typo3_intro_package/d' /etc/lighttpd/lighttpd-atv.conf
fi

if [ -f /etc/lighttpd.conf ];then
  sed -i '/mod_typo3_intro_package/d' /etc/lighttpd.conf
fi

exit 0

