#!/bin/sh

if [ $1 == remove ]; then
 if [ -d /var/www/dokuwiki ]; then
   rm -r /var/www/dokuwiki   
 fi
fi

if [ -f /etc/lighttpd/lighttpd-atv.conf ];then
  sed -i '/mod_dokuwiki/d' /etc/lighttpd/lighttpd-atv.conf
fi

if [ -f /etc/lighttpd.conf ];then
  sed -i '/mod_dokuwiki/d' /etc/lighttpd.conf
fi
 
exit 0

