#!/bin/sh

mv /etc/com.atv.mysql.my.cnf /etc/my.cnf

 echo " "
 echo " "

/usr/local/bin/mysql_install_db --user=daemon

echo "You will find the database files here: /var/mysql"
echo "You can start the Mysql server with the command below:"
echo "/usr/local/bin/mysqld_safe &"
echo "After that you have to set your MySQL root password:"
echo "/usr/local/bin/mysql_secure_installation" 

#During a package upgrade, the old packages scripts will stop and don't restart 'mysqld' -> Damn!
#Therefore we have to restart it again ....
if [ -f /Library/LaunchDaemons/com.atv.mysql.plist ]
then
 launchctl load -w /Library/LaunchDaemons/com.atv.mysql.plist
fi

echo " "
echo " "

exit 0



