#!/bin/sh
MYSQL=`ps -ax | grep '[m]ysql' | grep 'libexec' | awk '{ print $1 }'`
if [ "$MYSQL" != "" ]; then
 kill -s TERM $MYSQL # 2>&1 | true
fi

echo " "
echo " "
echo "Your database files are not deleted!"
echo "You will find they here: /var/mysql"
echo " "
echo " "

exit 0

